### ISSUE TITLE
Заменить на TryParse

### ISSUE THREAD

**Issue by sergoio0704** [IrbisV/TL#2]
https://github.com/IrbisV/TL/blob/e70e7725ce05a4fe036c851cec07a4f054660119/TL/ellipse/LearnCSharp/LearnCSharp/Program.cs#L7

Так как с консоли мы читаем всегда строку и приводим ее к определенному типу данных, может возникнуть исключение, когда исходную строку нельзя привести к нужному типу.

Сейчас, если вместо числа ввести, например, букву - возникает исключение(ошибка).

Чтобы обработать эту ситуацию, нужно заиспользовать метод TryParse.
Пример:
![image](https://user-images.githubusercontent.com/37891709/165600120-4456f986-dfa1-4b85-8a4a-85d9407036bf.png)

**Comment by IrbisV** [comment]
Использовал TryParse
https://github.com/IrbisV/TL/blob/d6160065910f11b18756c916393abe657917f2d6/TL/ellipse/LearnCSharp/LearnCSharp/Program.cs#L9-L12
https://github.com/IrbisV/TL/blob/d6160065910f11b18756c916393abe657917f2d6/TL/ellipse/LearnCSharp/LearnCSharp/Program.cs#L16-L18
