### ISSUE TITLE
Избавиться от else

### ISSUE THREAD

**Issue by sergoio0704** [IrbisV/TL#5]
https://github.com/IrbisV/TL/blob/e70e7725ce05a4fe036c851cec07a4f054660119/TL/ellipse/LearnCSharp/LearnCSharp/ellipse.cs#L21

В данной конструкции else не имеет смысла, так как если мы создадим и выбросим исключение, то программа попадет на уровень выше в блок catch.

Поэтому можно оставить только if

**Comment by IrbisV** [comment]
else убрал
